module.exports = {
  parserOptions: {
      ecmaVersion: '2020'
  },
  env: {
      mocha: true,
      node: true,
      es6: true
  },
  plugins: [
      'functional'
  ],
  rules: {
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-await-in-loop': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-console': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-extra-parens': 'error',
      'no-extra-semi': 'error',
      'no-func-assign': 'error',
      'no-import-assign': 'error',
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-misleading-character-class': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-regex-spaces': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'require-atomic-updates': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'accessor-pairs': 'error',
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      'class-methods-use-this': 'error',
      'complexity': 'error',
      'curly': 'error',
      'default-case': 'error',
      'default-param-last': 'error',
      'dot-notation': 'error',
      'eqeqeq': 'error',
      'grouped-accessor-pairs': 'error',
      'guard-for-in': 'error',
      'no-alert': 'error',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-constructor-return': 'error',
      'no-div-regex': 'error',
      'no-else-return': 'error',
      'no-empty-function': 'error',
      'no-empty-pattern': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-fallthrough': 'error',
      'no-floating-decimal': 'error',
      'no-global-assign': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'error',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-restricted-properties': 'error',
      'no-return-assign': 'error',
      'no-return-await': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'error',
      'no-unused-labels': 'error',
      'no-useless-call': 'error',
      'no-useless-catch': 'error',
      'no-useless-concat': 'error',
      'no-useless-escape': 'error',
      // ESLint functional plugin requires return statements in conditional blocks
      'no-useless-return': 'off',
      'no-void': 'error',
      'no-warning-comments': 'error',
      'no-with': 'error',
      'prefer-named-capture-group': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'error',
      'radix': 'error',
      'require-await': 'error',
      'require-unicode-regexp': 'error',
      'vars-on-top': 'error',
      'wrap-iife': 'error',
      'yoda': 'error',
      'strict': 'error',
      'no-delete-var': 'error',
      'no-label-var': 'error',
      'no-restricted-globals': 'error',
      'no-shadow-restricted-names': 'error',
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-unused-vars': 'error',
      'no-use-before-define': [
          'error',
          {
              'functions': false,
              'classes': false,
              'variables': true
          }
      ],
      'callback-return': 'error',
      'global-require': 'error',
      'handle-callback-err': 'error',
      'no-buffer-constructor': 'error',
      'no-mixed-requires': 'error',
      'no-new-require': 'error',
      'no-path-concat': 'error',
      'no-process-env': 'error',
      'no-process-exit': 'error',
      'no-restricted-modules': 'error',
      'array-bracket-newline': 'error',
      'array-bracket-spacing': 'error',
      'array-element-newline': ['error', "consistent"],
      'block-spacing': 'error',
      'brace-style': 'error',
      'camelcase': 'error',
      'comma-dangle': 'error',
      'comma-spacing': 'error',
      'comma-style': 'error',
      'computed-property-spacing': 'error',
      'consistent-this': 'error',
      'eol-last': 'error',
      'func-call-spacing': 'error',
      'func-name-matching': 'error',
      'func-names': ['error', 'never'],
      'function-paren-newline': 'error',
      'id-blacklist': 'error',
      'id-match': 'error',
      'implicit-arrow-linebreak': 'error',
      'indent': ['error', 2],
      'jsx-quotes': 'error',
      'key-spacing': 'error',
      'keyword-spacing': 'error',
      'linebreak-style': 'error',
      'lines-around-comment': 'error',
      'lines-between-class-members': 'error',
      'max-depth': 'warn',
      'max-lines': ['warn', {"max": 400, "skipComments": true, "skipBlankLines": true}],
      'max-nested-callbacks': 'warn',
      'max-params': ['warn', 4],
      'max-statements': ['warn', 20, { "ignoreTopLevelFunctions": true }],
      'max-statements-per-line': 'error',
      'new-cap': 'error',
      'new-parens': 'error',
      'no-array-constructor': 'error',
      'no-bitwise': 'error',
      'no-continue': 'error',
      'no-lonely-if': 'error',
      'no-mixed-operators': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-multi-assign': 'error',
      'no-multiple-empty-lines': 'error',
      'no-negated-condition': 'error',
      'no-nested-ternary': 'error',
      'no-new-object': 'error',
      'no-plusplus': 'error',
      'no-restricted-syntax': 'error',
      'no-tabs': 'error',
      'no-trailing-spaces': 'error',
      'no-unneeded-ternary': 'error',
      'no-whitespace-before-property': 'error',
      'nonblock-statement-body-position': 'error',
      'object-curly-newline': 'error',
      'object-curly-spacing': 'error',
      'one-var-declaration-per-line': 'error',
      'operator-assignment': 'error',
      'operator-linebreak': 'error',
      'padding-line-between-statements': 'error',
      'prefer-exponentiation-operator': 'error',
      'prefer-object-spread': 'error',
      'quotes': [
          'error',
          'single',
          {
              'avoidEscape': false,
              'allowTemplateLiterals': true
          }
      ],
      'semi': 'error',
      'semi-spacing': 'error',
      'semi-style': 'error',
      'space-before-blocks': 'error',
      'space-in-parens': 'error',
      'space-infix-ops': 'error',
      'space-unary-ops': 'error',
      'switch-colon-spacing': 'error',
      'template-tag-spacing': 'error',
      'unicode-bom': 'error',
      'wrap-regex': 'error',
      'arrow-body-style': 'error',
      'arrow-spacing': 'error',
      'constructor-super': 'error',
      'generator-star-spacing': 'error',
      'no-class-assign': 'error',
      'no-const-assign': 'error',
      'no-dupe-class-members': 'error',
      'no-duplicate-imports': 'error',
      'no-new-symbol': 'error',
      'no-restricted-imports': 'error',
      'no-this-before-super': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'error',
      'no-useless-rename': 'error',
      'no-var': 'error',
      'object-shorthand': 'error',
      'prefer-arrow-callback': 'error',
      'prefer-const': 'error',
      'prefer-destructuring': 'error',
      'prefer-numeric-literals': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'require-yield': 'error',
      'rest-spread-spacing': 'error',
      'symbol-description': 'error',
      'template-curly-spacing': 'error',
      'yield-star-spacing': 'error',
      'functional/immutable-data': 'error',
      'functional/no-let': 'error',
      'functional/no-this-expression': 'error',
      'functional/no-loop-statement': 'error',
      'functional/no-conditional-statement': [
          'error',
          {
              'allowReturningBranches': true
          }
      ]
  }
};
